# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Yichi Yang\Documents\Others\course planner\class_planner\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 700)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.addClassTab = QtWidgets.QWidget()
        self.addClassTab.setObjectName("addClassTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.addClassTab)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.promptLabel = QtWidgets.QLabel(self.addClassTab)
        self.promptLabel.setObjectName("promptLabel")
        self.verticalLayout_2.addWidget(self.promptLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.termLabel = QtWidgets.QLabel(self.addClassTab)
        self.termLabel.setObjectName("termLabel")
        self.horizontalLayout_3.addWidget(self.termLabel)
        self.termLineEdit = QtWidgets.QLineEdit(self.addClassTab)
        self.termLineEdit.setInputMask("")
        self.termLineEdit.setMaxLength(5)
        self.termLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.termLineEdit.setObjectName("termLineEdit")
        self.horizontalLayout_3.addWidget(self.termLineEdit)
        self.courseNameLabel = QtWidgets.QLabel(self.addClassTab)
        self.courseNameLabel.setObjectName("courseNameLabel")
        self.horizontalLayout_3.addWidget(self.courseNameLabel)
        self.classNameLineEdit = QtWidgets.QLineEdit(self.addClassTab)
        self.classNameLineEdit.setMaxLength(9)
        self.classNameLineEdit.setObjectName("classNameLineEdit")
        self.horizontalLayout_3.addWidget(self.classNameLineEdit)
        self.addClassButton = QtWidgets.QPushButton(self.addClassTab)
        self.addClassButton.setObjectName("addClassButton")
        self.horizontalLayout_3.addWidget(self.addClassButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.treeView = QtWidgets.QTreeView(self.addClassTab)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.tabWidget.addTab(self.addClassTab, "")
        self.setPolicyTab = QtWidgets.QWidget()
        self.setPolicyTab.setObjectName("setPolicyTab")
        self.gridLayout = QtWidgets.QGridLayout(self.setPolicyTab)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.setPolicyTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.earlyHorizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.earlyHorizontalSlider.setMinimum(-100)
        self.earlyHorizontalSlider.setMaximum(100)
        self.earlyHorizontalSlider.setProperty("value", 0)
        self.earlyHorizontalSlider.setSliderPosition(0)
        self.earlyHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.earlyHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.earlyHorizontalSlider.setTickInterval(50)
        self.earlyHorizontalSlider.setObjectName("earlyHorizontalSlider")
        self.horizontalLayout.addWidget(self.earlyHorizontalSlider)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.getUpEarlyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.getUpEarlyLabel.setObjectName("getUpEarlyLabel")
        self.horizontalLayout_2.addWidget(self.getUpEarlyLabel)
        self.earlyTimeEdit = QtWidgets.QTimeEdit(self.groupBox_2)
        self.earlyTimeEdit.setObjectName("earlyTimeEdit")
        self.horizontalLayout_2.addWidget(self.earlyTimeEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.setPolicyTab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.lateHorizontalSlider = QtWidgets.QSlider(self.groupBox_3)
        self.lateHorizontalSlider.setMinimum(-100)
        self.lateHorizontalSlider.setMaximum(100)
        self.lateHorizontalSlider.setProperty("value", 0)
        self.lateHorizontalSlider.setSliderPosition(0)
        self.lateHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lateHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.lateHorizontalSlider.setTickInterval(50)
        self.lateHorizontalSlider.setObjectName("lateHorizontalSlider")
        self.horizontalLayout_9.addWidget(self.lateHorizontalSlider)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.getUpEarlyLabel_4 = QtWidgets.QLabel(self.groupBox_3)
        self.getUpEarlyLabel_4.setObjectName("getUpEarlyLabel_4")
        self.horizontalLayout_10.addWidget(self.getUpEarlyLabel_4)
        self.lateTimeEdit = QtWidgets.QTimeEdit(self.groupBox_3)
        self.lateTimeEdit.setObjectName("lateTimeEdit")
        self.horizontalLayout_10.addWidget(self.lateTimeEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.setPolicyTab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.intervalHorizontalSlider = QtWidgets.QSlider(self.groupBox_4)
        self.intervalHorizontalSlider.setMinimum(-100)
        self.intervalHorizontalSlider.setMaximum(100)
        self.intervalHorizontalSlider.setProperty("value", 0)
        self.intervalHorizontalSlider.setSliderPosition(0)
        self.intervalHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.intervalHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.intervalHorizontalSlider.setTickInterval(50)
        self.intervalHorizontalSlider.setObjectName("intervalHorizontalSlider")
        self.horizontalLayout_11.addWidget(self.intervalHorizontalSlider)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.getUpEarlyLabel_5 = QtWidgets.QLabel(self.groupBox_4)
        self.getUpEarlyLabel_5.setObjectName("getUpEarlyLabel_5")
        self.horizontalLayout_12.addWidget(self.getUpEarlyLabel_5)
        self.intervalTimeEdit = QtWidgets.QTimeEdit(self.groupBox_4)
        self.intervalTimeEdit.setObjectName("intervalTimeEdit")
        self.horizontalLayout_12.addWidget(self.intervalTimeEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_12)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.setPolicyTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.requiredBreakLabel = QtWidgets.QLabel(self.groupBox)
        self.requiredBreakLabel.setObjectName("requiredBreakLabel")
        self.gridLayout_2.addWidget(self.requiredBreakLabel, 3, 0, 1, 1)
        self.intervalPenaltyLabel = QtWidgets.QLabel(self.groupBox)
        self.intervalPenaltyLabel.setObjectName("intervalPenaltyLabel")
        self.gridLayout_2.addWidget(self.intervalPenaltyLabel, 2, 0, 1, 1)
        self.latePenaltyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.latePenaltyLineEdit.setText("")
        self.latePenaltyLineEdit.setObjectName("latePenaltyLineEdit")
        self.gridLayout_2.addWidget(self.latePenaltyLineEdit, 1, 1, 1, 1)
        self.intervalPenaltyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.intervalPenaltyLineEdit.setText("")
        self.intervalPenaltyLineEdit.setObjectName("intervalPenaltyLineEdit")
        self.gridLayout_2.addWidget(self.intervalPenaltyLineEdit, 2, 1, 1, 1)
        self.earlyPenaltyLabel = QtWidgets.QLabel(self.groupBox)
        self.earlyPenaltyLabel.setObjectName("earlyPenaltyLabel")
        self.gridLayout_2.addWidget(self.earlyPenaltyLabel, 0, 0, 1, 1)
        self.requiredBreaksLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.requiredBreaksLineEdit.setText("")
        self.requiredBreaksLineEdit.setObjectName("requiredBreaksLineEdit")
        self.gridLayout_2.addWidget(self.requiredBreaksLineEdit, 3, 1, 1, 1)
        self.earlyPenaltyLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.earlyPenaltyLineEdit.setText("")
        self.earlyPenaltyLineEdit.setObjectName("earlyPenaltyLineEdit")
        self.gridLayout_2.addWidget(self.earlyPenaltyLineEdit, 0, 1, 1, 1)
        self.LatePenaltyLabel = QtWidgets.QLabel(self.groupBox)
        self.LatePenaltyLabel.setObjectName("LatePenaltyLabel")
        self.gridLayout_2.addWidget(self.LatePenaltyLabel, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.setPolicyTab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.breakHorizontalSlider = QtWidgets.QSlider(self.groupBox_5)
        self.breakHorizontalSlider.setMaximum(100)
        self.breakHorizontalSlider.setProperty("value", 20)
        self.breakHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.breakHorizontalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.breakHorizontalSlider.setTickInterval(25)
        self.breakHorizontalSlider.setObjectName("breakHorizontalSlider")
        self.gridLayout_3.addWidget(self.breakHorizontalSlider, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.breakStartTimeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.breakStartTimeEdit.setObjectName("breakStartTimeEdit")
        self.horizontalLayout_8.addWidget(self.breakStartTimeEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.breakEndTimeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.breakEndTimeEdit.setObjectName("breakEndTimeEdit")
        self.horizontalLayout_8.addWidget(self.breakEndTimeEdit)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.breakLenTimeEdit = QtWidgets.QTimeEdit(self.groupBox_5)
        self.breakLenTimeEdit.setObjectName("breakLenTimeEdit")
        self.horizontalLayout_8.addWidget(self.breakLenTimeEdit)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 0, 1, 4)
        self.addBreakPushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.addBreakPushButton.setObjectName("addBreakPushButton")
        self.gridLayout_3.addWidget(self.addBreakPushButton, 2, 0, 1, 4)
        self.breakTreeWidget = QtWidgets.QTreeWidget(self.groupBox_5)
        self.breakTreeWidget.setObjectName("breakTreeWidget")
        self.breakTreeWidget.header().setDefaultSectionSize(100)
        self.gridLayout_3.addWidget(self.breakTreeWidget, 3, 0, 1, 4)
        self.gridLayout.addWidget(self.groupBox_5, 0, 2, 3, 1)
        self.tabWidget.addTab(self.setPolicyTab, "")
        self.scheduleTab = QtWidgets.QWidget()
        self.scheduleTab.setObjectName("scheduleTab")
        self.scheduleTabHorizontalLayout = QtWidgets.QHBoxLayout(self.scheduleTab)
        self.scheduleTabHorizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.scheduleTabHorizontalLayout.setSpacing(6)
        self.scheduleTabHorizontalLayout.setObjectName("scheduleTabHorizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scheduleScoreTreeWidget = QtWidgets.QTreeWidget(self.scheduleTab)
        self.scheduleScoreTreeWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.scheduleScoreTreeWidget.setColumnCount(6)
        self.scheduleScoreTreeWidget.setObjectName("scheduleScoreTreeWidget")
        self.scheduleScoreTreeWidget.header().setDefaultSectionSize(80)
        self.verticalLayout.addWidget(self.scheduleScoreTreeWidget)
        self.scheduleDetailsTreeWidget = QtWidgets.QTreeWidget(self.scheduleTab)
        self.scheduleDetailsTreeWidget.setObjectName("scheduleDetailsTreeWidget")
        self.verticalLayout.addWidget(self.scheduleDetailsTreeWidget)
        self.updatPushButton = QtWidgets.QPushButton(self.scheduleTab)
        self.updatPushButton.setObjectName("updatPushButton")
        self.verticalLayout.addWidget(self.updatPushButton)
        self.scheduleTabHorizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.scheduleTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YYC\'s Course Planner"))
        self.promptLabel.setText(_translate("MainWindow", "Enter term and course name and click \"Add\"."))
        self.termLabel.setText(_translate("MainWindow", "Term Code:"))
        self.termLineEdit.setPlaceholderText(_translate("MainWindow", "20xxx"))
        self.courseNameLabel.setText(_translate("MainWindow", "Course Name:"))
        self.classNameLineEdit.setInputMask(_translate("MainWindow", "AAaa-999a"))
        self.classNameLineEdit.setText(_translate("MainWindow", "-"))
        self.classNameLineEdit.setPlaceholderText(_translate("MainWindow", "abcd-101"))
        self.addClassButton.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addClassTab), _translate("MainWindow", "My Course Bin"))
        self.groupBox_2.setTitle(_translate("MainWindow", "I love getting up early."))
        self.label.setText(_translate("MainWindow", "Yes"))
        self.label_2.setText(_translate("MainWindow", "No"))
        self.getUpEarlyLabel.setText(_translate("MainWindow", "How early is early?"))
        self.groupBox_3.setTitle(_translate("MainWindow", "I love getting home late."))
        self.label_7.setText(_translate("MainWindow", "Yes"))
        self.label_8.setText(_translate("MainWindow", "No"))
        self.getUpEarlyLabel_4.setText(_translate("MainWindow", "How late is late?"))
        self.groupBox_4.setTitle(_translate("MainWindow", "I love long breaks between classes."))
        self.label_9.setText(_translate("MainWindow", "Yes"))
        self.label_15.setText(_translate("MainWindow", "No"))
        self.getUpEarlyLabel_5.setText(_translate("MainWindow", "How long is long?"))
        self.groupBox.setTitle(_translate("MainWindow", "Advanced Config (disables corresponding intuitive policy setting)"))
        self.requiredBreakLabel.setText(_translate("MainWindow", "Required Breaks"))
        self.intervalPenaltyLabel.setText(_translate("MainWindow", "Interval Penalty"))
        self.latePenaltyLineEdit.setPlaceholderText(_translate("MainWindow", "(time1, penalty1), (time2, penalty2) ..."))
        self.intervalPenaltyLineEdit.setPlaceholderText(_translate("MainWindow", "(time1, penalty1), (time2, penalty2) ..."))
        self.earlyPenaltyLabel.setText(_translate("MainWindow", "Early Penalty"))
        self.requiredBreaksLineEdit.setPlaceholderText(_translate("MainWindow", "(start_time1, end_time1, length1, penalty1), (start_time2, end_time2, length2, penalty2) ..."))
        self.earlyPenaltyLineEdit.setPlaceholderText(_translate("MainWindow", "(time1, penalty1), (time2, penalty2) ..."))
        self.LatePenaltyLabel.setText(_translate("MainWindow", "Late Penalty"))
        self.groupBox_5.setTitle(_translate("MainWindow", "I need a break "))
        self.label_14.setText(_translate("MainWindow", "I mean it"))
        self.label_16.setText(_translate("MainWindow", "Don\'t care"))
        self.label_10.setText(_translate("MainWindow", "from around"))
        self.label_11.setText(_translate("MainWindow", "to"))
        self.label_12.setText(_translate("MainWindow", "and for"))
        self.label_13.setText(_translate("MainWindow", "(length)"))
        self.addBreakPushButton.setText(_translate("MainWindow", "Add"))
        self.breakTreeWidget.headerItem().setText(0, _translate("MainWindow", "Start"))
        self.breakTreeWidget.headerItem().setText(1, _translate("MainWindow", "End"))
        self.breakTreeWidget.headerItem().setText(2, _translate("MainWindow", "Length"))
        self.breakTreeWidget.headerItem().setText(3, _translate("MainWindow", "Cost"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setPolicyTab), _translate("MainWindow", "Scheduling Policy"))
        self.scheduleScoreTreeWidget.headerItem().setText(0, _translate("MainWindow", "Schedule"))
        self.scheduleScoreTreeWidget.headerItem().setText(1, _translate("MainWindow", "Total"))
        self.scheduleScoreTreeWidget.headerItem().setText(2, _translate("MainWindow", "Early"))
        self.scheduleScoreTreeWidget.headerItem().setText(3, _translate("MainWindow", "Late"))
        self.scheduleScoreTreeWidget.headerItem().setText(4, _translate("MainWindow", "Interval"))
        self.scheduleScoreTreeWidget.headerItem().setText(5, _translate("MainWindow", "Breaks"))
        self.scheduleDetailsTreeWidget.headerItem().setText(0, _translate("MainWindow", "Course"))
        self.scheduleDetailsTreeWidget.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.scheduleDetailsTreeWidget.headerItem().setText(2, _translate("MainWindow", "Section"))
        self.scheduleDetailsTreeWidget.headerItem().setText(3, _translate("MainWindow", "Time"))
        self.scheduleDetailsTreeWidget.headerItem().setText(4, _translate("MainWindow", "Days"))
        self.scheduleDetailsTreeWidget.headerItem().setText(5, _translate("MainWindow", "Registered"))
        self.scheduleDetailsTreeWidget.headerItem().setText(6, _translate("MainWindow", "Closed"))
        self.scheduleDetailsTreeWidget.headerItem().setText(7, _translate("MainWindow", "Instructor"))
        self.scheduleDetailsTreeWidget.headerItem().setText(8, _translate("MainWindow", "Location"))
        self.updatPushButton.setText(_translate("MainWindow", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scheduleTab), _translate("MainWindow", "Course Plan"))
